services:
  openldap1:
    image: bitnami/openldap:latest
    container_name: openldap1
    restart: always
    env_file:
      - .env
    networks:
      - openldap
    user: root
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - ./conf/ldifs:/ldifs
      - ./conf/schemas:/schemas
      - ./data/openldap_data1:/bitnami/openldap
  openldap2:
    image: bitnami/openldap:latest
    container_name: openldap2
    restart: always
    env_file:
      - .env
    networks:
      - openldap
    user: root
    ports:
      - "2389:1389"
      - "2636:1636"
    volumes:
      - ./conf/ldifs:/ldifs
      - ./conf/schemas:/schemas
      - ./data/openldap_data2:/bitnami/openldap
networks:
  openldap:
    external: true