services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    hostname: openldap
    environment:
      - LDAP_PORT_NUMBER=389
      - LDAP_ROOT=dc=jinnabalu,dc=com # jinnabalu.com
      - LDAP_ADMIN_USERNAME=ldapadmin
      - LDAP_ADMIN_PASSWORD=ldapadminpwd
      # - LDAP_ADMIN_PASSWORD_FILE=/home/ldif_files/ldapadminpwd # use the file instead of the env var LDAP_ADMIN_PASSWORD
      - LDAP_CONFIG_ADMIN_ENABLED=yes
      - LDAP_CONFIG_ADMIN_USERNAME=ldapadminconfig
      - LDAP_CONFIG_ADMIN_PASSWORD=ldapadminconfigpwd
      # - LDAP_CONFIG_ADMIN_PASSWORD_FILE=/home/ldif_files/ldapconfigpwd # use the env to replace LDAP_CONFIG_ADMIN_PASSWORD
      - LDAP_USERS=customuser1
      - LDAP_PASSWORDS=custompassword1
      - LDAP_ALLOW_ANON_BINDING=no
      - LDAP_USER_DC=People
      - LDAP_GROUP_DC=Group
      - LDAP_ADD_SCHEMAS=yes
      - LDAP_EXTRA_SCHEMAS=core,cosine,inetorgperson,nis
      - LDAP_SKIP_DEFAULT_TREE=no # yes, if you don't want to create any of the records from the above
      # - LDAP_CUSTOM_LDIF_DIR= /ldifs
      # - LDAP_CUSTOM_SCHEMA_DIR=/schemas
      # - LDAP_PASSWORD_HASH={SSHA}  #Options {SSHA}, {SHA}, {SMD5}, {MD5}, {CRYPT}, and {CLEARTEXT}. Default: {SSHA}.
      # - LDAP_CONFIGURE_PPOLICY=no # Enables the ppolicy module and creates an empty configuration. Default: no.
      - LDAP_LOGLEVEL=32768
      - LDAP_ENABLE_SYNCPROV=no # Set to yes, when multi-master is required
      - LDAP_SYNCPROV_CHECKPOINT="50 5" # Default: 100 10, 
      - LDAP_SYNCPROV_SESSIONLOG=100
    ports:
      - "1389:1389"
      - "1636:1636"
    volumes:
      - ./data/openldap:/bitnami/openldap
      # - ./data/ldifs:/ldifs # bootstraping these files while running
      # - ./data/schemas:/schemas # bootstraping these files while running
      - ./ldif_files:/home/ldif_files # if you want to use ldif files to add or modify
