services:
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    user: root
    env_file:
      - .env
    ports:
      - "${LDAP_PORT_NUMBER}:${LDAP_PORT_NUMBER}"
    volumes:
      - ./conf/ldifs:/ldifs
      - ./conf/schemas:/schemas
      - ./data/openldap_data:/bitnami/openldap