global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jhipster'
scrape_configs:
  - job_name: 'ldap_exporter'
    scrape_interval: 30s
    static_configs:
      - targets: [':9330']
